name: Core
main: Core\Loader
version: 1.0.0
api: 1.12.0
author: iksaku, MinePocket Developers
load: STARTUP

permissions:
  minepocket:
    default: false
    description: "Access to all the commands!"
    children:
     minepocket.login:
        default: false
        description: "Login to your account!"
     minepocket.register:
        default: false
        description: "Register a new account!"